export type DefaultCategoryTemplate = {
  key: string;
  parentKey: string | null;
  name: string;
  kind: "expense" | "income" | "investment" | "transfer";
  scope: "personal" | "business";
  sortOrder: number;
  description: string;
};

/**
 * Canonical version-1 category taxonomy mirrored by
 * 20260830000000_default_category_taxonomy.sql.
 */
export const DEFAULT_CATEGORY_TEMPLATES = [
  {
    key: "expense.food_and_dining",
    parentKey: null,
    name: "Food & Dining",
    kind: "expense",
    scope: "personal",
    sortOrder: 1,
    description: "Everyday food spending",
  },
  {
    key: "expense.food_and_dining.groceries",
    parentKey: "expense.food_and_dining",
    name: "Groceries",
    kind: "expense",
    scope: "personal",
    sortOrder: 2,
    description: "Supermarkets, kirana, meat, dairy and household food",
  },
  {
    key: "expense.food_and_dining.restaurants_and_cafes",
    parentKey: "expense.food_and_dining",
    name: "Restaurants & Cafes",
    kind: "expense",
    scope: "personal",
    sortOrder: 3,
    description: "Dine-in, takeaway, cafes and quick-service restaurants",
  },
  {
    key: "expense.food_and_dining.food_delivery",
    parentKey: "expense.food_and_dining",
    name: "Food Delivery",
    kind: "expense",
    scope: "personal",
    sortOrder: 4,
    description: "Prepared-food delivery and cloud kitchens",
  },
  {
    key: "expense.transport",
    parentKey: null,
    name: "Transport",
    kind: "expense",
    scope: "personal",
    sortOrder: 5,
    description: "Local commute and vehicle running costs",
  },
  {
    key: "expense.transport.cab_and_auto",
    parentKey: "expense.transport",
    name: "Cab & Auto",
    kind: "expense",
    scope: "personal",
    sortOrder: 6,
    description: "Taxi, auto-rickshaw and bike taxi",
  },
  {
    key: "expense.transport.public_transport",
    parentKey: "expense.transport",
    name: "Public Transport",
    kind: "expense",
    scope: "personal",
    sortOrder: 7,
    description: "Bus and metro",
  },
  {
    key: "expense.transport.fuel",
    parentKey: "expense.transport",
    name: "Fuel",
    kind: "expense",
    scope: "personal",
    sortOrder: 8,
    description: "Petrol, diesel, CNG and EV charging",
  },
  {
    key: "expense.transport.parking_and_tolls",
    parentKey: "expense.transport",
    name: "Parking & Tolls",
    kind: "expense",
    scope: "personal",
    sortOrder: 9,
    description: "Parking, tolls and FASTag",
  },
  {
    key: "expense.transport.vehicle_maintenance",
    parentKey: "expense.transport",
    name: "Vehicle Maintenance",
    kind: "expense",
    scope: "personal",
    sortOrder: 10,
    description: "Service, repairs, tyres and spares",
  },
  {
    key: "expense.housing_and_utilities",
    parentKey: null,
    name: "Housing & Utilities",
    kind: "expense",
    scope: "personal",
    sortOrder: 11,
    description: "Home occupancy and recurring utilities",
  },
  {
    key: "expense.housing_and_utilities.rent",
    parentKey: "expense.housing_and_utilities",
    name: "Rent",
    kind: "expense",
    scope: "personal",
    sortOrder: 12,
    description: "Home rent and rental platforms",
  },
  {
    key: "expense.housing_and_utilities.society_maintenance",
    parentKey: "expense.housing_and_utilities",
    name: "Society Maintenance",
    kind: "expense",
    scope: "personal",
    sortOrder: 13,
    description: "Apartment and housing-society charges",
  },
  {
    key: "expense.housing_and_utilities.electricity",
    parentKey: "expense.housing_and_utilities",
    name: "Electricity",
    kind: "expense",
    scope: "personal",
    sortOrder: 14,
    description: "Electricity bills",
  },
  {
    key: "expense.housing_and_utilities.water",
    parentKey: "expense.housing_and_utilities",
    name: "Water",
    kind: "expense",
    scope: "personal",
    sortOrder: 15,
    description: "Water bills",
  },
  {
    key: "expense.housing_and_utilities.cooking_gas",
    parentKey: "expense.housing_and_utilities",
    name: "Cooking Gas",
    kind: "expense",
    scope: "personal",
    sortOrder: 16,
    description: "Piped gas and LPG",
  },
  {
    key: "expense.housing_and_utilities.mobile_and_internet",
    parentKey: "expense.housing_and_utilities",
    name: "Mobile & Internet",
    kind: "expense",
    scope: "personal",
    sortOrder: 17,
    description: "Mobile, landline and broadband",
  },
  {
    key: "expense.housing_and_utilities.tv_and_dth",
    parentKey: "expense.housing_and_utilities",
    name: "TV & DTH",
    kind: "expense",
    scope: "personal",
    sortOrder: 18,
    description: "DTH and cable television",
  },
  {
    key: "expense.household",
    parentKey: null,
    name: "Household",
    kind: "expense",
    scope: "personal",
    sortOrder: 19,
    description: "Home services and durable goods",
  },
  {
    key: "expense.household.domestic_help",
    parentKey: "expense.household",
    name: "Domestic Help",
    kind: "expense",
    scope: "personal",
    sortOrder: 20,
    description: "Maid, cook, driver and household staff",
  },
  {
    key: "expense.household.home_repairs",
    parentKey: "expense.household",
    name: "Home Repairs",
    kind: "expense",
    scope: "personal",
    sortOrder: 21,
    description: "Cleaning, repairs, pest control and maintenance",
  },
  {
    key: "expense.household.furniture_and_appliances",
    parentKey: "expense.household",
    name: "Furniture & Appliances",
    kind: "expense",
    scope: "personal",
    sortOrder: 22,
    description: "Furniture, appliances and home improvement",
  },
  {
    key: "expense.health_and_medical",
    parentKey: null,
    name: "Health & Medical",
    kind: "expense",
    scope: "personal",
    sortOrder: 23,
    description: "Healthcare excluding insurance premiums",
  },
  {
    key: "expense.health_and_medical.doctor_and_hospital",
    parentKey: "expense.health_and_medical",
    name: "Doctor & Hospital",
    kind: "expense",
    scope: "personal",
    sortOrder: 24,
    description: "Consultations, procedures and hospitalization",
  },
  {
    key: "expense.health_and_medical.medicines",
    parentKey: "expense.health_and_medical",
    name: "Medicines",
    kind: "expense",
    scope: "personal",
    sortOrder: 25,
    description: "Pharmacy and medicine purchases",
  },
  {
    key: "expense.health_and_medical.diagnostics",
    parentKey: "expense.health_and_medical",
    name: "Diagnostics",
    kind: "expense",
    scope: "personal",
    sortOrder: 26,
    description: "Labs, scans and health tests",
  },
  {
    key: "expense.health_and_medical.dental_and_vision",
    parentKey: "expense.health_and_medical",
    name: "Dental & Vision",
    kind: "expense",
    scope: "personal",
    sortOrder: 27,
    description: "Dentist, optical and eye care",
  },
  {
    key: "expense.insurance",
    parentKey: null,
    name: "Insurance",
    kind: "expense",
    scope: "personal",
    sortOrder: 28,
    description: "Insurance premium payments",
  },
  {
    key: "expense.insurance.health_insurance",
    parentKey: "expense.insurance",
    name: "Health Insurance",
    kind: "expense",
    scope: "personal",
    sortOrder: 29,
    description: "Health and medical insurance",
  },
  {
    key: "expense.insurance.life_insurance",
    parentKey: "expense.insurance",
    name: "Life Insurance",
    kind: "expense",
    scope: "personal",
    sortOrder: 30,
    description: "Term, endowment and life policies",
  },
  {
    key: "expense.insurance.vehicle_insurance",
    parentKey: "expense.insurance",
    name: "Vehicle Insurance",
    kind: "expense",
    scope: "personal",
    sortOrder: 31,
    description: "Motor and two-wheeler insurance",
  },
  {
    key: "expense.insurance.other_insurance",
    parentKey: "expense.insurance",
    name: "Other Insurance",
    kind: "expense",
    scope: "personal",
    sortOrder: 32,
    description: "Travel, home and general insurance",
  },
  {
    key: "expense.education",
    parentKey: null,
    name: "Education",
    kind: "expense",
    scope: "personal",
    sortOrder: 33,
    description: "Formal education and skills",
  },
  {
    key: "expense.education.school_and_college_fees",
    parentKey: "expense.education",
    name: "School & College Fees",
    kind: "expense",
    scope: "personal",
    sortOrder: 34,
    description: "School, college and institutional fees",
  },
  {
    key: "expense.education.tuition_and_courses",
    parentKey: "expense.education",
    name: "Tuition & Courses",
    kind: "expense",
    scope: "personal",
    sortOrder: 35,
    description: "Coaching, online courses and tuition",
  },
  {
    key: "expense.education.books_and_supplies",
    parentKey: "expense.education",
    name: "Books & Supplies",
    kind: "expense",
    scope: "personal",
    sortOrder: 36,
    description: "Books, uniforms and learning supplies",
  },
  {
    key: "expense.shopping",
    parentKey: null,
    name: "Shopping",
    kind: "expense",
    scope: "personal",
    sortOrder: 37,
    description: "Personal and household retail",
  },
  {
    key: "expense.shopping.clothing_and_footwear",
    parentKey: "expense.shopping",
    name: "Clothing & Footwear",
    kind: "expense",
    scope: "personal",
    sortOrder: 38,
    description: "Apparel, footwear and accessories",
  },
  {
    key: "expense.shopping.electronics",
    parentKey: "expense.shopping",
    name: "Electronics",
    kind: "expense",
    scope: "personal",
    sortOrder: 39,
    description: "Devices and consumer electronics",
  },
  {
    key: "expense.shopping.home_and_kitchen",
    parentKey: "expense.shopping",
    name: "Home & Kitchen",
    kind: "expense",
    scope: "personal",
    sortOrder: 40,
    description: "Homeware, kitchenware and decor",
  },
  {
    key: "expense.shopping.beauty_and_personal_care",
    parentKey: "expense.shopping",
    name: "Beauty & Personal Care",
    kind: "expense",
    scope: "personal",
    sortOrder: 41,
    description: "Salon, spa, cosmetics and grooming",
  },
  {
    key: "expense.shopping.kids_and_baby",
    parentKey: "expense.shopping",
    name: "Kids & Baby",
    kind: "expense",
    scope: "personal",
    sortOrder: 42,
    description: "Baby products, toys and children's retail",
  },
  {
    key: "expense.entertainment_and_subscriptions",
    parentKey: null,
    name: "Entertainment & Subscriptions",
    kind: "expense",
    scope: "personal",
    sortOrder: 43,
    description: "Leisure and recurring digital services",
  },
  {
    key: "expense.entertainment_and_subscriptions.movies_and_events",
    parentKey: "expense.entertainment_and_subscriptions",
    name: "Movies & Events",
    kind: "expense",
    scope: "personal",
    sortOrder: 44,
    description: "Cinema, concerts, events and tickets",
  },
  {
    key: "expense.entertainment_and_subscriptions.streaming_services",
    parentKey: "expense.entertainment_and_subscriptions",
    name: "Streaming Services",
    kind: "expense",
    scope: "personal",
    sortOrder: 45,
    description: "Video, music and news streaming",
  },
  {
    key: "expense.entertainment_and_subscriptions.software_and_apps",
    parentKey: "expense.entertainment_and_subscriptions",
    name: "Software & Apps",
    kind: "expense",
    scope: "personal",
    sortOrder: 46,
    description: "Productivity software, cloud and app subscriptions",
  },
  {
    key: "expense.entertainment_and_subscriptions.games_and_hobbies",
    parentKey: "expense.entertainment_and_subscriptions",
    name: "Games & Hobbies",
    kind: "expense",
    scope: "personal",
    sortOrder: 47,
    description: "Gaming, sports and hobbies",
  },
  {
    key: "expense.travel",
    parentKey: null,
    name: "Travel",
    kind: "expense",
    scope: "personal",
    sortOrder: 48,
    description: "Outstation and holiday travel",
  },
  {
    key: "expense.travel.flights",
    parentKey: "expense.travel",
    name: "Flights",
    kind: "expense",
    scope: "personal",
    sortOrder: 49,
    description: "Air tickets and airline charges",
  },
  {
    key: "expense.travel.trains_and_buses",
    parentKey: "expense.travel",
    name: "Trains & Buses",
    kind: "expense",
    scope: "personal",
    sortOrder: 50,
    description: "Rail and intercity bus travel",
  },
  {
    key: "expense.travel.hotels_and_stay",
    parentKey: "expense.travel",
    name: "Hotels & Stay",
    kind: "expense",
    scope: "personal",
    sortOrder: 51,
    description: "Hotels, hostels and holiday accommodation",
  },
  {
    key: "expense.travel.travel_services",
    parentKey: "expense.travel",
    name: "Travel Services",
    kind: "expense",
    scope: "personal",
    sortOrder: 52,
    description: "Booking portals, tours, visa and travel services",
  },
  {
    key: "expense.family_and_lifestyle",
    parentKey: null,
    name: "Family & Lifestyle",
    kind: "expense",
    scope: "personal",
    sortOrder: 53,
    description: "Social, family and lifestyle commitments",
  },
  {
    key: "expense.family_and_lifestyle.gifts",
    parentKey: "expense.family_and_lifestyle",
    name: "Gifts",
    kind: "expense",
    scope: "personal",
    sortOrder: 54,
    description: "Personal gifts and social obligations",
  },
  {
    key: "expense.family_and_lifestyle.festivals_and_religious",
    parentKey: "expense.family_and_lifestyle",
    name: "Festivals & Religious",
    kind: "expense",
    scope: "personal",
    sortOrder: 55,
    description: "Festivals, ceremonies and religious expenses",
  },
  {
    key: "expense.family_and_lifestyle.weddings_and_functions",
    parentKey: "expense.family_and_lifestyle",
    name: "Weddings & Functions",
    kind: "expense",
    scope: "personal",
    sortOrder: 56,
    description: "Weddings, parties and functions",
  },
  {
    key: "expense.family_and_lifestyle.pets",
    parentKey: "expense.family_and_lifestyle",
    name: "Pets",
    kind: "expense",
    scope: "personal",
    sortOrder: 57,
    description: "Pet food, healthcare and supplies",
  },
  {
    key: "expense.loans_and_emi",
    parentKey: null,
    name: "Loans & EMI",
    kind: "expense",
    scope: "personal",
    sortOrder: 58,
    description: "Debt servicing excluding credit-card settlement",
  },
  {
    key: "expense.loans_and_emi.home_loan_emi",
    parentKey: "expense.loans_and_emi",
    name: "Home Loan EMI",
    kind: "expense",
    scope: "personal",
    sortOrder: 59,
    description: "Home-loan EMI and interest",
  },
  {
    key: "expense.loans_and_emi.vehicle_loan_emi",
    parentKey: "expense.loans_and_emi",
    name: "Vehicle Loan EMI",
    kind: "expense",
    scope: "personal",
    sortOrder: 60,
    description: "Vehicle-loan EMI and interest",
  },
  {
    key: "expense.loans_and_emi.personal_loan_emi",
    parentKey: "expense.loans_and_emi",
    name: "Personal Loan EMI",
    kind: "expense",
    scope: "personal",
    sortOrder: 61,
    description: "Personal, gold and education-loan EMI",
  },
  {
    key: "expense.loans_and_emi.consumer_emi",
    parentKey: "expense.loans_and_emi",
    name: "Consumer EMI",
    kind: "expense",
    scope: "personal",
    sortOrder: 62,
    description: "BNPL and consumer-durable EMI",
  },
  {
    key: "expense.taxes_and_fees",
    parentKey: null,
    name: "Taxes & Fees",
    kind: "expense",
    scope: "personal",
    sortOrder: 63,
    description: "Taxes, banking and statutory fees",
  },
  {
    key: "expense.taxes_and_fees.income_and_property_tax",
    parentKey: "expense.taxes_and_fees",
    name: "Income & Property Tax",
    kind: "expense",
    scope: "personal",
    sortOrder: 64,
    description: "Income, advance and property tax",
  },
  {
    key: "expense.taxes_and_fees.bank_charges",
    parentKey: "expense.taxes_and_fees",
    name: "Bank Charges",
    kind: "expense",
    scope: "personal",
    sortOrder: 65,
    description: "Bank and card charges",
  },
  {
    key: "expense.taxes_and_fees.government_fees",
    parentKey: "expense.taxes_and_fees",
    name: "Government Fees",
    kind: "expense",
    scope: "personal",
    sortOrder: 66,
    description: "Stamp duty and government service fees",
  },
  {
    key: "expense.taxes_and_fees.penalties_and_processing_fees",
    parentKey: "expense.taxes_and_fees",
    name: "Penalties & Processing Fees",
    kind: "expense",
    scope: "personal",
    sortOrder: 67,
    description: "Late, convenience, processing and foreclosure fees",
  },
  {
    key: "expense.business_expenses",
    parentKey: null,
    name: "Business Expenses",
    kind: "expense",
    scope: "business",
    sortOrder: 68,
    description: "Compact business-expense defaults",
  },
  {
    key: "expense.business_expenses.office_and_coworking",
    parentKey: "expense.business_expenses",
    name: "Office & Coworking",
    kind: "expense",
    scope: "business",
    sortOrder: 69,
    description: "Office rent, utilities and coworking",
  },
  {
    key: "expense.business_expenses.inventory_and_supplies",
    parentKey: "expense.business_expenses",
    name: "Inventory & Supplies",
    kind: "expense",
    scope: "business",
    sortOrder: 70,
    description: "Inventory, raw material, packaging and logistics",
  },
  {
    key: "expense.business_expenses.payroll_and_contractors",
    parentKey: "expense.business_expenses",
    name: "Payroll & Contractors",
    kind: "expense",
    scope: "business",
    sortOrder: 71,
    description: "Payroll, contractors and employee costs",
  },
  {
    key: "expense.business_expenses.marketing_and_sales",
    parentKey: "expense.business_expenses",
    name: "Marketing & Sales",
    kind: "expense",
    scope: "business",
    sortOrder: 72,
    description: "Advertising, promotions and commissions",
  },
  {
    key: "expense.business_expenses.professional_services",
    parentKey: "expense.business_expenses",
    name: "Professional Services",
    kind: "expense",
    scope: "business",
    sortOrder: 73,
    description: "Legal, accounting, consulting and audit",
  },
  {
    key: "expense.business_expenses.software_and_saas",
    parentKey: "expense.business_expenses",
    name: "Software & SaaS",
    kind: "expense",
    scope: "business",
    sortOrder: 74,
    description: "Business software, cloud and hosting",
  },
  {
    key: "expense.business_expenses.business_travel",
    parentKey: "expense.business_expenses",
    name: "Business Travel",
    kind: "expense",
    scope: "business",
    sortOrder: 75,
    description: "Business travel and client entertainment",
  },
  {
    key: "expense.business_expenses.business_taxes_and_fees",
    parentKey: "expense.business_expenses",
    name: "Business Taxes & Fees",
    kind: "expense",
    scope: "business",
    sortOrder: 76,
    description: "GST, compliance, licences and business banking fees",
  },
  {
    key: "expense.charity_and_donations",
    parentKey: null,
    name: "Charity & Donations",
    kind: "expense",
    scope: "personal",
    sortOrder: 77,
    description: "Verified charity and donation payments",
  },
  {
    key: "expense.uncategorized",
    parentKey: null,
    name: "Uncategorized",
    kind: "expense",
    scope: "personal",
    sortOrder: 78,
    description: "Fallback only; never an AI-preferred category",
  },
  {
    key: "income.income",
    parentKey: null,
    name: "Income",
    kind: "income",
    scope: "personal",
    sortOrder: 79,
    description: "All incoming money",
  },
  {
    key: "income.income.salary_and_income",
    parentKey: "income.income",
    name: "Salary & Income",
    kind: "income",
    scope: "personal",
    sortOrder: 80,
    description: "Salary, wages, bonus and pension",
  },
  {
    key: "income.income.business_income",
    parentKey: "income.income",
    name: "Business Income",
    kind: "income",
    scope: "business",
    sortOrder: 81,
    description: "Sales, freelance and professional receipts",
  },
  {
    key: "income.income.interest_and_dividends",
    parentKey: "income.income",
    name: "Interest & Dividends",
    kind: "income",
    scope: "personal",
    sortOrder: 82,
    description: "Interest, dividends and capital distributions",
  },
  {
    key: "income.income.rental_income",
    parentKey: "income.income",
    name: "Rental Income",
    kind: "income",
    scope: "personal",
    sortOrder: 83,
    description: "Property rental receipts",
  },
  {
    key: "income.income.refunds_and_reimbursements",
    parentKey: "income.income",
    name: "Refunds & Reimbursements",
    kind: "income",
    scope: "personal",
    sortOrder: 84,
    description: "Refunds, cashback and reimbursements",
  },
  {
    key: "income.income.other_income",
    parentKey: "income.income",
    name: "Other Income",
    kind: "income",
    scope: "personal",
    sortOrder: 85,
    description: "Income not covered elsewhere",
  },
  {
    key: "investment.investments",
    parentKey: null,
    name: "Investments",
    kind: "investment",
    scope: "personal",
    sortOrder: 86,
    description: "Asset purchases and long-term savings",
  },
  {
    key: "investment.investments.mutual_funds_and_sip",
    parentKey: "investment.investments",
    name: "Mutual Funds & SIP",
    kind: "investment",
    scope: "personal",
    sortOrder: 87,
    description: "Mutual funds and systematic plans",
  },
  {
    key: "investment.investments.stocks_and_etfs",
    parentKey: "investment.investments",
    name: "Stocks & ETFs",
    kind: "investment",
    scope: "personal",
    sortOrder: 88,
    description: "Brokerage, stocks and exchange-traded funds",
  },
  {
    key: "investment.investments.fixed_income_and_deposits",
    parentKey: "investment.investments",
    name: "Fixed Income & Deposits",
    kind: "investment",
    scope: "personal",
    sortOrder: 89,
    description: "FD, RD, bonds and debt products",
  },
  {
    key: "investment.investments.retirement_savings",
    parentKey: "investment.investments",
    name: "Retirement Savings",
    kind: "investment",
    scope: "personal",
    sortOrder: 90,
    description: "PPF, EPF and NPS",
  },
  {
    key: "investment.investments.gold_and_commodities",
    parentKey: "investment.investments",
    name: "Gold & Commodities",
    kind: "investment",
    scope: "personal",
    sortOrder: 91,
    description: "Digital gold, sovereign gold and commodities",
  },
  {
    key: "transfer.transfers",
    parentKey: null,
    name: "Transfers",
    kind: "transfer",
    scope: "personal",
    sortOrder: 92,
    description: "Non-income/non-expense money movement",
  },
  {
    key: "transfer.transfers.self_transfer",
    parentKey: "transfer.transfers",
    name: "Self Transfer",
    kind: "transfer",
    scope: "personal",
    sortOrder: 93,
    description: "Transfers between own accounts",
  },
  {
    key: "transfer.transfers.bank_transfer",
    parentKey: "transfer.transfers",
    name: "Bank Transfer",
    kind: "transfer",
    scope: "personal",
    sortOrder: 94,
    description: "NEFT, IMPS and RTGS transfers without a merchant purpose",
  },
  {
    key: "transfer.transfers.wallet_top_up",
    parentKey: "transfer.transfers",
    name: "Wallet Top-up",
    kind: "transfer",
    scope: "personal",
    sortOrder: 95,
    description: "Loading a wallet or prepaid balance",
  },
  {
    key: "transfer.transfers.credit_card_payment",
    parentKey: "transfer.transfers",
    name: "Credit Card Payment",
    kind: "transfer",
    scope: "personal",
    sortOrder: 96,
    description: "Credit-card bill settlement",
  },
  {
    key: "transfer.transfers.cash_and_atm",
    parentKey: "transfer.transfers",
    name: "Cash & ATM",
    kind: "transfer",
    scope: "personal",
    sortOrder: 97,
    description: "Cash withdrawal and cash deposit",
  },
  {
    key: "transfer.transfers.loan_principal",
    parentKey: "transfer.transfers",
    name: "Loan Principal",
    kind: "transfer",
    scope: "personal",
    sortOrder: 98,
    description: "Principal-only debt movement when separately identified",
  },
] as const satisfies readonly DefaultCategoryTemplate[];

export const DEFAULT_CATEGORY_NAMES = DEFAULT_CATEGORY_TEMPLATES.map((template) => template.name);
