import http from "node:http";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CLIENT_DIR = path.resolve(__dirname, "dist/client");
const PORT = process.env.PORT ? parseInt(process.env.PORT, 10) : 3000;
const HOST = process.env.HOST || "0.0.0.0";

// Import the SSR server handler generated by TanStack Start
const serverModule = await import("./dist/server/server.js");
const handler = serverModule.default?.fetch || serverModule.fetch;

if (!handler) {
  console.error("Error: Could not find fetch handler in dist/server/server.js");
  process.exit(1);
}

const MIME_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".txt": "text/plain; charset=utf-8",
};

function tryServeStatic(req, res) {
  const urlPath = new URL(req.url, `http://${req.headers.host || "localhost"}`).pathname;
  let decodedPath;
  try {
    decodedPath = decodeURIComponent(urlPath);
  } catch {
    return false;
  }

  // Prevent directory traversal
  const filePath = path.normalize(path.join(CLIENT_DIR, decodedPath));
  if (!filePath.startsWith(CLIENT_DIR)) return false;

  // Don't serve index.html statically directly if SSR should handle root
  if (decodedPath === "/" || decodedPath === "") return false;

  try {
    if (fs.existsSync(filePath) && fs.statSync(filePath).isFile()) {
      const ext = path.extname(filePath).toLowerCase();
      const contentType = MIME_TYPES[ext] || "application/octet-stream";
      
      // Cache assets with hashed names aggressively
      const isHashed = decodedPath.startsWith("/assets/") || decodedPath.includes("-");
      const cacheControl = isHashed
        ? "public, max-age=31536000, immutable"
        : "public, max-age=3600";

      res.writeHead(200, {
        "Content-Type": contentType,
        "Cache-Control": cacheControl,
      });

      fs.createReadStream(filePath).pipe(res);
      return true;
    }
  } catch {
    return false;
  }
  return false;
}

// Convert Node IncomingMessage to Web Standard Request
async function createWebRequest(req) {
  const protocol = req.socket.encrypted ? "https" : "http";
  const host = req.headers.host || "localhost:3000";
  const url = `${protocol}://${host}${req.url}`;

  const headers = new Headers();
  for (const [key, value] of Object.entries(req.headers)) {
    if (value === undefined) continue;
    if (Array.isArray(value)) {
      for (const v of value) headers.append(key, v);
    } else {
      headers.set(key, value);
    }
  }

  const init = {
    method: req.method,
    headers,
  };

  if (req.method !== "GET" && req.method !== "HEAD") {
    // Collect body buffers
    const chunks = [];
    for await (const chunk of req) {
      chunks.push(chunk);
    }
    if (chunks.length > 0) {
      init.body = Buffer.concat(chunks);
    }
  }

  return new Request(url, init);
}

// Stream Web Standard Response to Node ServerResponse
async function sendWebResponse(webRes, res) {
  const headers = {};
  webRes.headers.forEach((val, key) => {
    headers[key] = val;
  });

  res.writeHead(webRes.status, headers);

  if (webRes.body) {
    const reader = webRes.body.getReader();
    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        res.write(Buffer.from(value));
      }
    } finally {
      reader.releaseLock();
    }
  }
  res.end();
}

const server = http.createServer(async (req, res) => {
  try {
    // 1. Try static assets first
    if (tryServeStatic(req, res)) return;

    // 2. Pass to SSR handler
    const webRequest = await createWebRequest(req);
    const webResponse = await handler(webRequest, {}, {});
    await sendWebResponse(webResponse, res);
  } catch (err) {
    console.error("[Server Error]:", err);
    if (!res.headersSent) {
      res.writeHead(500, { "Content-Type": "text/plain; charset=utf-8" });
      res.end("Internal Server Error");
    }
  }
});

server.listen(PORT, HOST, () => {
  console.log(`\n  🟢 Paisa production server running at: http://${HOST === "0.0.0.0" ? "localhost" : HOST}:${PORT}\n`);
});
